<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ADaxer.MvvmNav.Avalonia</RootNamespace>
    <AssemblyName>ADaxer.MvvmNav.Avalonia</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\MvvmNav.Core.csproj" />
    <ProjectReference Include="..\Abstractions\MvvmNav.Abstractions.csproj" />
  </ItemGroup>

</Project>
