<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-macos'">
    <OutputType>Exe</OutputType>
    <UseAppHost>true</UseAppHost>
    <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
    <ApplicationId>com.adaxer.mvvmnav.sample</ApplicationId>

    <!-- DAS ist der entscheidende Punkt -->
    <EnableMacOSAppHost>true</EnableMacOSAppHost>
  </PropertyGroup>
  
  <PropertyGroup>
    <!--If you are willing to use platform-specific APIs, use conditional compilation.
    See https://docs.avaloniaui.net/docs/guides/platforms/platform-specific-code/dotnet for more details.-->
    <TargetFrameworks>net10.0;net10.0-macos</TargetFrameworks>
    <Nullable>enable</Nullable>
    <RootNamespace>ADaxer.MvvmNav.Sample.Avalonia.Desktop</RootNamespace>
    <AssemblyName>ADaxer.MvvmNav.Sample.Avalonia.Desktop</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="..\Sample.Avalonia\Assets\mvvmnav.png" Link="Assets\mvvmnav.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="Tmds.DBus.Protocol" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sample.Avalonia\Sample.Avalonia.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-macos'">
    <Content Remove="..\..\Common\Sample.Common\markdown\**" />
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <None Include="Platforms/MacOS/Info.plist">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <Content Include="AppIcon.icns">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Assets\markdown\" />
  </ItemGroup>
</Project>
