<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ADaxer.MvvmNav.Sample.Common</RootNamespace>
    <AssemblyName>ADaxer.MvvmNav.Sample.Common</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="markdown\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="ADaxer.MvvmNav.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Abstractions\MvvmNav.Abstractions.csproj" />
  </ItemGroup>
</Project>
